name: general

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.9
  - astropy=6.0.0
  - h5py=3.10.0
  - httplib2=0.22.0
  - imageio=2.34
  - imageio-ffmpeg=0.4.9
  - jupyterlab=4.1.4
  - matplotlib=3.8.3
  - moviepy=1.0.3
  - numba=0.59.0
  - numpy=1.26.4
  - packaging=23.2
  - pandas=2.2.1
  - pyhdf=0.11.3
  - pytest=8.0.2
  - requests=2.31.0
  - scipy=1.12.0
  - sunpy=5.1.1
  - spyder-kernels=2.5
  - pytables=3.9.2
  - pyqt=5.15.10
  
  
